name: RDTravelingBanker
version: '${project.version}'
main: ru.rivendell.rdtravelingbanker.RDTravelingBanker
api-version: '1.20'
dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
      join-classpath: true